### ISSUE TITLE
Error if pageorloc formatting deviates from expected format

### ISSUE THREAD

**Issue by j-chan-hkust** [paperboi/kindle2notion#11]
I have experienced the following error:
Traceback (most recent call last):
  File "kindle2notion.py", line 200, in <module>
    ch = KindleClippings(CLIPPINGS_FILE)
  File "kindle2notion.py", line 13, in __init__
    self.clippings = self._getAllClippings(clippingsFile)
  File "kindle2notion.py", line 18, in _getAllClippings
    return self._parseClippings(allClippings)
  File "kindle2notion.py", line 96, in _parseClippings
    self.addToNotion(lastClip)
  File "kindle2notion.py", line 185, in addToNotion
    title = "Page: " + lastClip['Page'] + "\tDate Added: " +  str(lastClip['Date Added'].strftime("%A, %d %B %Y %I:%M:%S %p"))
TypeError: must be str, not NoneType

The cause is that my Kindle is storing my strings as: 
- Your Highlight on Location 

Which is a bit of a deviation from what kindle2notion expects.

I think its probably easier to make the parsing here a bit more robust, probably by doing the following:
- convert case down to lower to make it case agnostic
- attempt to find substring "page" or "location" in order to check if it is a page or a location
- filter out all characters which are not digits or hyphens in order to get the meaningful information

May suggest this as a push.

**Comment by pranavkaranjkar** [comment]
@j-chan-hkust After looking at your suggestion, I was able to fix part of the code. However, I still get an error while executing. Would you mind looking at the other issue I raised? Thanks!

**Comment by paperboi** [comment]
Hey, thanks for raising this! Sorry for the late reply! Will look into implementing a feature to take all these subtle variations in formats into account.

**Comment by xbassi** [comment]
@paperboi linked the commit here #284021522ddcd65689cdc1858ddb8f5387fd54d3

**Comment by xbassi** [comment]
#10

**Comment by paperboi** [comment]
@j-chan-hkust implemented your suggestions as a fix. Thanks for the help!
