### ISSUE TITLE
Line 9 error import CLIPPINGS_FILE, NOTION_TOKEN, NOTION_TABLE_ID

### ISSUE THREAD

**Issue by felipefm** [paperboi/kindle2notion#13]
I just finished the installation, when I ran the terminal I was giving an error on lines 40 and 49. I couldn't solve it.

So I installed pycharm, I'm using a Linux Mint 20.0 distribution

I would like to test the script, I am looking for a script or app that has interaction with Kindle and Notion.

Thank you.

**Comment by paperboi** [comment]
Are you running this script using Python 3? And can you copy-paste the error you're getting if possible?
Sorry for the late reply, couldn't make time for this in my work schedule earlier.

**Comment by paperboi** [comment]
Addressed this by moving imported vars to utilities.py in [the latest commit](https://github.com/paperboi/kindle2notion/tree/284021522ddcd65689cdc1858ddb8f5387fd54d3)
