### ISSUE TITLE
Problems with `notion-py`

### ISSUE THREAD

**Issue by lhrinaldi** [paperboi/kindle2notion#14]
Apparently `notion-py` has some issues with big http limits.

https://github.com/jamalex/notion-py/issues/304

A workaround for me (a noob on python) to make it work was:

1. Run `pip show notion` on the terminal.
2. Get notion package location and access its contents (e.g. `/usr/local/lib/python3.9/site-packages/notion`).
3. Change `store.py` line 280 to `"limit": 100,`.

**Comment by lhrinaldi** [comment]
Thanks for this great package by the way. Works like a charm.

**Comment by paperboi** [comment]
Wow. Thanks for the heads up! Will keep this pinned for future reference.

**Comment by aryaMode** [comment]
This does not work for me.

**Comment by Predo7** [comment]
this doesn't work for me

**Comment by acakebro** [comment]
it worked for me!

**Comment by Rexus752** [comment]
Thanks, it worked!

**Comment by necessaryBQ** [comment]
Thanks, it worked for me!

**Comment by DWJCW** [comment]
It worked for me! Thank you!

**Comment by zEduardofaria** [comment]
It worked! Thanks much

**Comment by triet-lq-holistics** [comment]
Thanks, it worked gracefully on my local. Anyone has any idea how to make this change on production?

**Comment by Nagi-no-Asukara** [comment]
thanks

**Comment by everyoneloveme1** [comment]
wow!!! it works!!!  big thanks to you!
