### ISSUE TITLE
Excellent tool 👏

### ISSUE THREAD

**Issue by trungk18** [paperboi/kindle2notion#19]
Hey Jeffrey,

I found your script today and currently migrating all of my kindle notes to notion. Thank you so much for that code. It saves me lots of time :)

I want to get you a coffee for writing this code. Would you feel like creating a [Buy me a coffee](https://www.buymeacoffee.com/) page so that others could also donate for you?

**Comment by paperboi** [comment]
Thank you so much for writing this @trungk18, it made my week! I'll see if I can get a BMAC page set up and update on this thread and the README.md. :)

**Comment by trungk18** [comment]
Sure, let me know once you have a page. It should be super easy to setup. You did great!

**Comment by paperboi** [comment]
You can find me [here](https://www.buymeacoffee.com/jeffreyjacob). Added a link in the README too. Highly appreciate your support!

**Comment by trungk18** [comment]
Thanks man, I have some problem with paypal and seems I need a new paypal account before I can get you a coffee 🤣

**Comment by paperboi** [comment]
> 
> 
> Thanks man, I have some problem with paypal and seems I need a new paypal account before I can get you a coffee 🤣

No worries, take your time. I appreciate the sentiment!
