### ISSUE TITLE
Exception trying to extract title and author

### ISSUE THREAD

**Issue by djemeljanovs** [paperboi/kindle2notion#2]
Given a complex book title consisting of more than one word in brackets, for example:
 `Смерть Ивана Ильича (Russian Edition) (Толстой, Лев Николаевич)`

The following exception is thrown:
`
Traceback (most recent call last):
  File "kindle2notion.py", line 242, in <module>
    ch = KindleClippings(CLIPPINGS_FILE)
  File "kindle2notion.py", line 13, in __init__
    self.clippings = self._getAllClippings(clippingsFile)
  File "kindle2notion.py", line 18, in _getAllClippings
    return self._parseClippings(allClippings)
  File "kindle2notion.py", line 27, in _parseClippings
    title, author = title_author.split('|')
ValueError: too many values to unpack (expected 2)
`

**Comment by paperboi** [comment]
Just saw this push request. Thanks for the contribution!

**Comment by djemeljanovs** [comment]
Thank you for sharing your tool here! I have found it extremely useful to review notes from the books I read.
