### ISSUE TITLE
Script Issues

### ISSUE THREAD

**Issue by VatanaChhorn** [paperboi/kindle2notion#21]
I'm tryna running the script, but this error log has occurred. 

python3 kindle2notion.py
Notion page is found. Analyzing clippings file...

Found 328 notes and highlights.

'str' object has no attribute 'removeprefix'
Exiting script...
sh: pause: command not found

**Comment by paperboi** [comment]
Hey, thanks for bringing this up!
Please check if your Python version is upto date.
`str.removeprefix()` and `str.removesuffix()` functions are supported from v3.9 onwards.

**Comment by VatanaChhorn** [comment]
I've sort if out, but here comes another problem. 

Traceback (most recent call last):
  File "/Users/vatanachhorn/Desktop/Kindle2Notion/kindle2notion.py", line 1, in <module>
    from notion.collection import NotionDate
ModuleNotFoundError: No module named 'notion'

**Comment by VatanaChhorn** [comment]
I've worked it out! 

Thanks for bare with me, and keep up the good work ; )

**Comment by VatanaChhorn** [comment]
btw, do I need to create a new workspace every time I export the highlights to the notion, or the code is automatically ignoring the duplicate highlight?

**Comment by paperboi** [comment]
> 
> 
> btw, do I need to create a new workspace every time I export the highlights to Notion, or the code is automatically ignoring the duplicate highlight?

So the code checks for new highlights by comparing the total number of clippings under each book with the number of highlights listed on its respective Notion page. And replace the entire text under that page with the updated clippings. I did this to save the number of APIs calls.
You would only have to create the workspace and set up the environment vars once. 
You may need to update your Notion token every couple months tho, which is normal.
Hope this helps. Check out the code and let me know if it works out. Cheers!
