### ISSUE TITLE
Code fails when Author information isn't present in the clippings file

### ISSUE THREAD

**Issue by rahulakrishna** [paperboi/kindle2notion#25]
Noticed that some Kindle titles don't have Author information. I faced this issue with "The Intelligent Investor" that I bought from the Kindle Store. 

While it doesn't seem possible to fetch the Author info, it can be made so the code gracefully fails and uses an empty string for Author Name. I used a fix locally to get around the issue. Will make a PR later today if this issue is accepted.

Attaching images of clippings file and error message below.

<img width="962" alt="image" src="https://user-images.githubusercontent.com/10240002/119225687-e3333c00-bb22-11eb-8455-2cb56e79d083.png">

<img width="723" alt="image" src="https://user-images.githubusercontent.com/10240002/119225755-6f456380-bb23-11eb-8615-816003daceeb.png">

**Comment by paperboi** [comment]
Hi @rahulakrishna ! Thanks for raising this issue! Wasn't aware of this particular case with Kindle books. Will merge your changes with the main repo.
