### ISSUE TITLE
Thumbnails fetched from Google Book API are not visible on browser

### ISSUE THREAD

**Issue by paperboi** [paperboi/kindle2notion#30]
Picture below for reference.

![image](https://user-images.githubusercontent.com/26799318/119572683-c6239500-bdd0-11eb-94b7-818e666e2efc.png)

**Comment by theneo13** [comment]
For me its the other way round. Thumbnails are visible in browser, but not in Windows10 app and Android App.

**Comment by paperboi** [comment]
For some reason, this keeps happening on Firefox. Your solution worked for Chrome and Microsoft Edge (I assume it must be the same for all other Chromium browsers).

**Comment by guptaanmol184** [comment]
Hi @paperboi ,

Sure, I can check out the issue further in the weekend and get back. 

I do want to add that I had only tested with firefox, and the fix did seem to resolve the issue for me. If there are any specific details on how you are testing, can you please share them  as might provide more information on the steps to reproduce and the cases to check ?

**Comment by paperboi** [comment]
> 
> 
> Hi @paperboi , Sure, I can check out the issue further in the weekend and get back.
> 
> I do want to add that I had only tested with firefox, for that is the main browser that I use, and the fix did seem to resolve the issue for me. If there are any specific details on how you are testing, can you please share them as might provide more information on the steps to reproduce and the cases I might be missing to check ?

Got it working finally! Had to make some considerations in the code to fetch from any response JSON objects with an `imageLinks` property than just the first responses'. Books with multiple editions may have missing covers or multiple covers and the current code would only check whether the first response JSON object would have a thumbnail. Wrote a for loop to go through all possible results and fetch the first one with a thumbnail listed.

Implemented the solution in the latest release. Thanks for contributing to the repo!

**Comment by guptaanmol184** [comment]
Glad to hear that, that's definately a better approach to handle adding missing book covers. Cheers!
