### ISSUE TITLE
Not writing to Notion

### ISSUE THREAD

**Issue by dieggywegz** [paperboi/kindle2notion#4]
I've followed instructions and don't get an error upon executing the command, but the clippings are not actually written to the Notion database. In fact, the database remains unchanged from the template.

![image](https://user-images.githubusercontent.com/50031236/98625871-7b1dc500-234b-11eb-8a78-947e3545a923.png)

Pop OS 20.10
Kindle Paperwhite (3rd Gen)

**Comment by paperboi** [comment]
Retraced the steps and it worked for me. Can you crosscheck your NOTION_TABLE_ID and NOTION_TOKEN?

**Comment by ckabut** [comment]
Hey Paperboi, I am expecting the same issue like dieggywegz
Kinder Paperwhite

NOTION_TOKEN is ok - if I am changing the value I have got an authentification errors
NOTION_TABLE_ID - I am not sure - I am copying the full url address "https://www.notion.so/1wtxxxx...."

If I am using only "1wtxxx..." as parameter, I have got such error:
AssertionError: If 'url_or_id' is an ID (not a URL), you must also pass the 'collection'

**Comment by AnilRh** [comment]
@dieggywegz Could you provide an example Clipping from your My Clippings text file? 

I had the same issue. In my case the code was looking for "Your Highlight at location" while my clippings contained "Your Highlight On Location". Since they didn't match the clipping was ignored. (I also had to change some date formatting code for US date format support - so perhaps that's why my text was different too).

**Comment by paperboi** [comment]
> 
> 
> @dieggywegz Could you provide an example Clipping from your My Clippings text file?
> 
> I had the same issue. In my case the code was looking for "Your Highlight at location" while my clippings contained "Your Highlight On Location". Since they didn't match the clipping was ignored. (I also had to change some date formatting code for US date format support - so perhaps that's why my text was different too).

Can you pls add your changes as a possible use case in the code? From what I have seen so far, the date formats for different Kindle models in different countries are widely different and it would be great if our code could cater to as many formats as possible.
