### ISSUE TITLE
Invalid collection view URL

### ISSUE THREAD

**Issue by alitanirlar** [paperboi/kindle2notion#42]
~ kindle2notion '53daebe5e31867d66528004e6f9b209f8e95889af9e39aad3ba6a774336e39edc78b39a8323c817c36f9cdaefa64085a494f0a89c2af2c26ca96ccab9e9ca301c3b11a************' 'https://www.notion.so/*******/ecd48369d2f64b53bfae2ad349afc264\?v\=a2fd7fae297f4a6999010e8d168c767c' '/Volumes/Kindle/documents/My\ Clippings.txt'
Traceback (most recent call last):
  File "/usr/local/bin/kindle2notion", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/kindle2notion/__main__.py", line 32, in main
    notion_collection_view = notion_client.get_collection_view(notion_table_id)
  File "/usr/local/lib/python3.9/site-packages/notion/client.py", line 163, in get_collection_view
    raise Exception("Invalid collection view URL")
Exception: Invalid collection view URL

**Comment by paperboi** [comment]
Chances are your Notion token may have changed. Can you crosscheck this and update here?

**Comment by hitamu** [comment]
I'm facing this problem too @paperboi

**Comment by hitamu** [comment]
Tried logout & login again (new token_v2) The error is still happen.

**Comment by hitamu** [comment]
Tried with full URL https://www.notion.so/4db799037ba44e52xxxxxxxxxx?v=7aba7f0e9b754yyyyyyyyyyyyy
It's working now.

**Comment by paperboi** [comment]
> 
> 
> Tried with full URL https://www.notion.so/4db799037ba44e52xxxxxxxxxx?v=7aba7f0e9b754yyyyyyyyyyyyy
> It's working now.

Hi, can you please elaborate on what change you made to get it working?

**Comment by anshulahuja98** [comment]
@alitanirlar I faced this issue when working from the source code.
The issue I realised is that 
in the URL, there is the part *\?v\=*
The backslash sometimes get "escaped" as \\.

Solution:  I would suggest removing the "\" before and after v and then try again. It should probably resolve the issue for you.

**Comment by paperboi** [comment]
Closing this as the issue doesn't correspond to the current iteration of the package. Update the package and read through the docs for the updated setup.
