### ISSUE TITLE
AttributeError: 'str' object has no attribute 'removeprefix'

### ISSUE THREAD

**Issue by starmadegeek** [paperboi/kindle2notion#44]
Trying to emulate the process laid down in the README.md file.
Got this error. The script successfully identified the clippings file and the notion table but not able to complete the process.

**Initial output:**
```
Notion page is found. Analyzing clippings file...
Found 105 notes and highlights.
```

**Showing error in this line:** 
```
kindle2notion\parsing.py", line 69, in _parse_raw_author_and_title
 author = author.removeprefix('(').removesuffix(')')
AttributeError: 'str' object has no attribute 'removeprefix'
```

**Comment by Bergene** [comment]
Hi.

What python version are you using? 
'removeprefix' is a new feature introduced in Python 3.9.

**Comment by starmadegeek** [comment]
Hi,
My python version was 3.8.3.
Sorry my bad. I didn't know about the features in 3.9. Anyway I fixed it by implementing those functions myself.
Thanks for clarifying.

**Comment by paperboi** [comment]
Hi @starmadegeek, this is a duplicate issue. Please refer to #27.
Basically, update your Python version to the latest version (3.9+).
