### ISSUE TITLE
Error: Got unexpected extra argument (Clippings.txt') - in Windows 10

### ISSUE THREAD

**Issue by Gonzaloif** [paperboi/kindle2notion#51]
Hi! I'm writting from Chile, the program seems awesome!
I have no skills at all in coding but I followed the steps and managed to install python, pip and kindle 2notion package. Could you please help me out? Thanx a lot!!!! I would really appreciate it!

`C:\Program Files\Python39>py -m kindle2notion 
.... (i deleted the token, url and kindle path from the message i got)

Usage: python -m kindle2notion [OPTIONS] NOTION_TOKEN NOTION_TABLE_ID
                               CLIPPINGS_FILE_PATH
Try 'python -m kindle2notion --help' for help.

Error: Got unexpected extra argument (Clippings.txt')`

**Comment by paperboi** [comment]
Try enclosing each argument (the Notion token, table ID and clippings file path) in single quotes and run the command.

**Comment by Gonzaloif** [comment]
> Try enclosing each argument (the Notion token, table ID and clippings file path) in single quotes and run the command.

perfect! i tried using double quote enclosing each argument and worked just fine, thanx a lot!!!! Awesome program you made!
