### ISSUE TITLE
Issues in Notion API, 400 error, library broken

### ISSUE THREAD

**Issue by anshulahuja98** [paperboi/kindle2notion#64]
The library has broken due to issues in the notion unofficial API

https://github.com/jamalex/notion-py/issues/351

Refer above issue

**Comment by ShuibCodes** [comment]
> .

HI, whats the status on this issue?

**Comment by jgajera** [comment]
Bump - I'm also facing this issue

**Comment by ShawnAviles** [comment]
Also facing a similar issue

**Comment by victorterancas** [comment]
Facing the same issue.

**Comment by paperboi** [comment]
Hi @anshulahuja98 , I rewrote the code from the ground up. It now relies on [notional](https://github.com/jheddings/notional) for the read/write operations to the Notion database. It should be working smoothly now.
