### ISSUE TITLE
IsADirectoryError: [Errno 21] Is a directory: '/Volumes/Kindle/documents/My Clippings.sdr'

### ISSUE THREAD

**Issue by ShuibCodes** [paperboi/kindle2notion#65]
i keep getting this error 
IsADirectoryError: [Errno 21] Is a directory: '/Volumes/Kindle/documents/My Clippings.sdr'

this happens when i tried to first run the command with the table URL, my token and the clippings path

**Comment by paperboi** [comment]
Hi, just came across this. You're supposed to use the My Clippings text file (.txt extension).
