### ISSUE TITLE
requests.exceptions.HTTPError: Invalid input.

### ISSUE THREAD

**Issue by Predo7** [paperboi/kindle2notion#69]
I tried running the script and i get this error.

I already tried this solution but nothing #14 

(i'm very noob in programmation :))

**Comment by SchluppiBobbz** [comment]
For me this solution worked: https://github.com/jamalex/notion-py/pull/294#issuecomment-804306525 

Also described here: 
https://stackoverflow.com/questions/66513210/cant-get-page-title-from-notion-using-api

Copy pasted from stackoverflow:
pip uninstall notion

Then either:

pip install git+https://github.com/jamalex/notion-py.git@refs/pull/294/merge
OR in your requirements.txt add

git+https://github.com/jamalex/notion-py.git@refs/pull/294/merge

I hope that helps,
Best

**Comment by paperboi** [comment]
Hi, I switched to a different python SDK for the official Notion API in the latest commits. The updated package has been released on PyPi as well. Please run it and hope it works for you.
