### ISSUE TITLE
Can't install kindle2notion. setuptools not available in the build environment.

### ISSUE THREAD

**Issue by nashitahmedbarq** [paperboi/kindle2notion#70]
C:\Users\Nashit Ahmed Barq>python -m pip install kindle2notion
Collecting kindle2notion
  Using cached kindle2notion-0.1.8.tar.gz (11 kB)
  Preparing metadata (setup.py) ... done
Collecting click>=8.0.0
  Using cached click-8.0.4-py3-none-any.whl (97 kB)
Collecting dateparser>=1.0.0
  Using cached dateparser-1.1.0-py2.py3-none-any.whl (288 kB)
Collecting DateTime>=4.3
  Using cached DateTime-4.4-py2.py3-none-any.whl (51 kB)
Collecting notion>=0.0.27
  Using cached notion-0.0.28-py3-none-any.whl (43 kB)
Collecting python-decouple>=3.3
  Using cached python_decouple-3.6-py3-none-any.whl (9.9 kB)
Collecting requests>=2.25.0
  Using cached requests-2.27.1-py2.py3-none-any.whl (63 kB)
Collecting pathlib
  Using cached pathlib-1.0.1.tar.gz (49 kB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [1 lines of output]
      **ERROR: Can not execute `setup.py` since setuptools is not available in the build environment.**
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.

**Comment by lihuelworks** [comment]
Same here, any updates on this?

**Comment by nashitahmedbarq** [comment]
> Same here, any updates on this?

You can use a chrome extension to export your highlights to notion. 

Here's the link:

https://chrome.google.com/webstore/detail/export-kindle-highlights/nmgbhgbkbenpfjkdfladebgcdihbekne

**Comment by nashitahmedbarq** [comment]
> Thanks for answering Nasha! I'll try it out. Also, I think the problem may be the use of pathlib on the requirements. Apparently it's not being mantained anymore, and it's encouraged to use pathlib2 (which didn't gave me errors when modifying requirements.txt to use it).
> 
> I'm using Windows 10 with Python 3.8

You're very welcome.

**Comment by paperboi** [comment]
> Thanks for answering Nasha! I'll try it out. Also, I think the problem may be the use of pathlib on the requirements. Apparently it's not being mantained anymore, and it's encouraged to use pathlib2 (which didn't gave me errors when modifying requirements.txt to use it).
> 
> I'm using Windows 10 with Python 3.8

Apologies for only getting around to this now but please update Python to 3.9 or more for the code to work as intended.

@nashitahmedbarq @lihuelworks
