### ISSUE TITLE
Issues with running the script

### ISSUE THREAD

**Issue by flintstones-fred** [paperboi/kindle2notion#9]
I am getting an error - 

`Traceback (most recent call last):
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 9, in <module>
    from settings import CLIPPINGS_FILE, NOTION_TOKEN, NOTION_TABLE_ID
  File "/Users/Pranav/Tools/Kindle2Notion/settings.py", line 5, in <module>
    CLIPPINGS_FILE = config('CLIPPINGS_FILE')
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decouple.py", line 199, in __call__
    return self.config(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decouple.py", line 83, in __call__
    return self.get(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decouple.py", line 68, in get
    raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option))
decouple.UndefinedValueError: CLIPPINGS_FILE not found. Declare it as envvar or define a default value.`

It seems that I am not storing the path to the clipping file correctly. But I can't tell what's going wrong - 

Content of kindle2notion.env file:
`CLIPPINGS_FILE = "/Users/Pranav/Tools/Kindle2Notion/MyClippings.txt"
NOTION_TOKEN = "fe606a84504eeac4***"
NOTION_TABLE_ID = "1fa082d598e34df***"
`

**Comment by pranavkaranjkar** [comment]
I think I figured out my problem! However, I am now getting the following error: 

[
  <TableView (id='b0b21bc6-c57d-4305-aeb0-00edde335e48')>,
  <GalleryView (id='f668e530-8c09-4995-8f9a-928006c09895')>,
  <ListView (id='cb061611-8c62-4ca0-bc53-e35b4d4e6243')>,
]
Found 107 notes and highlights
Processing note/highlight number 1 / 107 from The Dark Tower (Stephen King)
Traceback (most recent call last):
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 221, in <module>
    ch = KindleClippings(CLIPPINGS_FILE)
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 14, in __init__
    self.clippings = self._getAllClippings(clippingsFile)
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 19, in _getAllClippings
    return self._parseClippings(allClippings)
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 109, in _parseClippings
    self.addToNotion(lastClip)
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 204, in addToNotion
    title="Page: " + lastClip['Page'] + "\tDate Added: " + str(

TypeError: can only concatenate str (not "NoneType") to str

**Comment by pranavkaranjkar** [comment]
@paperboi After fixing the script for the issue j-chan-hkust raised. I am still getting an error. 

Traceback (most recent call last):
  File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 216, in <module>
    client = NotionClient(token_v2=NOTION_TOKEN)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notion/client.py", line 68, in __init__
    self._update_user_info()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notion/client.py", line 75, in _update_user_info
    self._store.store_recordmap(records)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/notion/store.py", line 292, in store_recordmap
    for id, record in records.items():
AttributeError: 'NoneType' object has no attribute 'items'

Can you help? Thanks!

**Comment by petebdeblois** [comment]
Hi @pranavkaranjkar 
I updated the notion to 0.0.28 and it solved the AttributeError: 'NoneType' object has no attribute 'items'
Issue here -> https://github.com/jamalex/notion-py/pull/270

**Comment by francesconotarianni** [comment]
> I think I figured out my problem! However, I am now getting the following error:
> 
> [
> <TableView (id='b0b21bc6-c57d-4305-aeb0-00edde335e48')>,
> <GalleryView (id='f668e530-8c09-4995-8f9a-928006c09895')>,
> <ListView (id='cb061611-8c62-4ca0-bc53-e35b4d4e6243')>,
> ]
> Found 107 notes and highlights
> Processing note/highlight number 1 / 107 from The Dark Tower (Stephen King)
> Traceback (most recent call last):
> File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 221, in
> ch = KindleClippings(CLIPPINGS_FILE)
> File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 14, in **init**
> self.clippings = self._getAllClippings(clippingsFile)
> File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 19, in _getAllClippings
> return self._parseClippings(allClippings)
> File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 109, in _parseClippings
> self.addToNotion(lastClip)
> File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 204, in addToNotion
> title="Page: " + lastClip['Page'] + "\tDate Added: " + str(
> 
> TypeError: can only concatenate str (not "NoneType") to str

How did you solve that problem? I'm having the same error show up.

Keep in mind I'm a beginner with programming, so if you could explain like I was 5 it'd be greatly appreciated.

Thanks in advance!!

**Comment by francesconotarianni** [comment]
> > I think I figured out my problem! However, I am now getting the following error:
> > 
> > [
> > <TableView (id='b0b21bc6-c57d-4305-aeb0-00edde335e48')>,
> > <GalleryView (id='f668e530-8c09-4995-8f9a-928006c09895')>,
> > <ListView (id='cb061611-8c62-4ca0-bc53-e35b4d4e6243')>,
> > ]
> > Found 107 notes and highlights
> > Processing note/highlight number 1 / 107 from The Dark Tower (Stephen King)
> > Traceback (most recent call last):
> > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 221, in
> > ch = KindleClippings(CLIPPINGS_FILE)
> > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 14, in **init**
> > self.clippings = self._getAllClippings(clippingsFile)
> > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 19, in _getAllClippings
> > return self._parseClippings(allClippings)
> > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 109, in _parseClippings
> > self.addToNotion(lastClip)
> > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 204, in addToNotion
> > title="Page: " + lastClip['Page'] + "\tDate Added: " + str(
> > 
> > TypeError: can only concatenate str (not "NoneType") to str
> 
> How did you solve that problem? I'm having the same error show up.
> 
> Keep in mind I'm a beginner with programming, so if you could explain like I was 5 it'd be greatly appreciated.
> 
> Thanks in advance!!

Ok, I've manually changed the names of the various files in the settings.py file.

Right now a new arror appears:

`Traceback (most recent call last):
File "C:\Users\franc\Desktop\Desktop\File download vari\Kindle to Notion\kindle2notion.py", line 151, in <module>
cv = client.get_collection_view(NOTION_TABLE_ID)
File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 165, in get_collection_view
collection = self.get_block(
File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 118, in get_block
block = self.get_record_data("block", block_id, force_refresh=force_refresh)
File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 111, in get_record_data
return self._store.get(table, id, force_refresh=force_refresh)
File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\store.py", line 184, in get
self.call_load_page_chunk(id)
File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\store.py", line 286, in call_load_page_chunk
recordmap = self._client.post("loadPageChunk", data).json()["recordMap"]
File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 209, in post
raise HTTPError(
requests.exceptions.HTTPError: Invalid input.`

What can I do?

**Comment by acter-khan** [comment]
> I am getting an error -
> 
> `Traceback (most recent call last): File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 9, in <module> from settings import CLIPPINGS_FILE, NOTION_TOKEN, NOTION_TABLE_ID File "/Users/Pranav/Tools/Kindle2Notion/settings.py", line 5, in <module> CLIPPINGS_FILE = config('CLIPPINGS_FILE') File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decouple.py", line 199, in __call__ return self.config(*args, **kwargs) File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decouple.py", line 83, in __call__ return self.get(*args, **kwargs) File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/decouple.py", line 68, in get raise UndefinedValueError('{} not found. Declare it as envvar or define a default value.'.format(option)) decouple.UndefinedValueError: CLIPPINGS_FILE not found. Declare it as envvar or define a default value.`
> 
> It seems that I am not storing the path to the clipping file correctly. But I can't tell what's going wrong -
> 
> Content of kindle2notion.env file:
> `CLIPPINGS_FILE = "/Users/Pranav/Tools/Kindle2Notion/MyClippings.txt" NOTION_TOKEN = "fe606a84504eeac4***" NOTION_TABLE_ID = "1fa082d598e34df***" `

What was the fix for this? I am experiencing the same error.

**Comment by paperboi** [comment]
Addressed this in #17

**Comment by paperboi** [comment]
> 
> 
> > > I think I figured out my problem! However, I am now getting the following error:
> > > [
> > > <TableView (id='b0b21bc6-c57d-4305-aeb0-00edde335e48')>,
> > > <GalleryView (id='f668e530-8c09-4995-8f9a-928006c09895')>,
> > > <ListView (id='cb061611-8c62-4ca0-bc53-e35b4d4e6243')>,
> > > ]
> > > Found 107 notes and highlights
> > > Processing note/highlight number 1 / 107 from The Dark Tower (Stephen King)
> > > Traceback (most recent call last):
> > > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 221, in
> > > ch = KindleClippings(CLIPPINGS_FILE)
> > > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 14, in **init**
> > > self.clippings = self._getAllClippings(clippingsFile)
> > > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 19, in _getAllClippings
> > > return self._parseClippings(allClippings)
> > > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 109, in _parseClippings
> > > self.addToNotion(lastClip)
> > > File "/Users/Pranav/Tools/Kindle2Notion/kindle2notion.py", line 204, in addToNotion
> > > title="Page: " + lastClip['Page'] + "\tDate Added: " + str(
> > > TypeError: can only concatenate str (not "NoneType") to str
> > 
> > 
> > How did you solve that problem? I'm having the same error show up.
> > Keep in mind I'm a beginner with programming, so if you could explain like I was 5 it'd be greatly appreciated.
> > Thanks in advance!!
> 
> Ok, I've manually changed the names of the various files in the settings.py file.
> 
> Right now a new arror appears:
> 
> `Traceback (most recent call last): File "C:\Users\franc\Desktop\Desktop\File download vari\Kindle to Notion\kindle2notion.py", line 151, in <module> cv = client.get_collection_view(NOTION_TABLE_ID) File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 165, in get_collection_view collection = self.get_block( File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 118, in get_block block = self.get_record_data("block", block_id, force_refresh=force_refresh) File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 111, in get_record_data return self._store.get(table, id, force_refresh=force_refresh) File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\store.py", line 184, in get self.call_load_page_chunk(id) File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\store.py", line 286, in call_load_page_chunk recordmap = self._client.post("loadPageChunk", data).json()["recordMap"] File "C:\Users\franc\AppData\Local\Programs\Python\Python39\lib\site-packages\notion\client.py", line 209, in post raise HTTPError( requests.exceptions.HTTPError: Invalid input.`
> 
> What can I do?

@francesconotarianni pls see #16 and #17. Sure it'd address the issues you're facing.

**Comment by paperboi** [comment]
Solution to all yours issues in #16 and #17.
Find my reply to this particular error [here](https://github.com/paperboi/kindle2notion/issues/17#issuecomment-826094278)

Removed lastClip variable entirely in the latest commit [here](https://github.com/paperboi/kindle2notion/tree/284021522ddcd65689cdc1858ddb8f5387fd54d3)
